---
title: "Lab 3 : Graphing with ggplot"
output:
  html_document:
    toc: true
    toc_depth: 4
    theme: united
    highlight: tango
editor_options: 
  chunk_output_type: console
---

## Learning objectives

* ggplot

## Introduction to R Graphics

R provides comprehensive graphics utilities for visualizing and exploring scientific data. To date we have been making a few plots using the R Base Graphics. In addition, several more recent graphics environments extend these utilities. These include the `grid`, `lattice` and `ggplot2` packages. The `ggplot2` environment is by far the most popular and used for many R packages and in many scientific publications. 

### Grammar of Graphics

`ggplot2` is meant to be an implementation of the Grammar of Graphics, hence the gg in ggplot. The basic notion is that there is a grammar to the composition of graphical components in statistical graphics. By direcly controlling that grammar, you can generate a large set of carefully constructed graphics from a relatively small set of operations. As Hadley Wickham (2010), the author of `ggplot2` said,

"A good grammar will allow us to gain insight into the composition of complicated graphics, and reveal unexpected connections between seemingly different graphics.

### Installation

`ggplot2` is a R package, which is part of the `tidyverse` collection. 

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

### Tutorials and resources

You can make amazing graphs with ggplot, but there is a long learning curve so we will have multiple lab sessions on ggplot and graphing. Here are a few different resources for `ggplot`.

* Hadley Wickham and Garrett Grolemund released a new book in 2017 [R for Data Science](http://r4ds.had.co.nz/).  Chapter 3 covers material related to this week's lab in ggplot.
* Another resource good for those with a visual learning style is [Maria Nattestad's Youtube videos](https://www.youtube.com/channel/UC2bWYX9h1KlaGWfTDuhASWg)
* [ggplot cheatsheet](https://github.com/rstudio/cheatsheets/blob/master/data-visualization-2.1.pdf)

### Key board shortcuts

* Selecting `shift` `ctrl` `m` at the same time is a keyboard shortcut for `%
* Selecting `ctr` `alt` `i` at the same time is a keyboard shortcut for a new r code (Windows keyboard layout)
* Selecting `option` `command` `i` at the same time is a keyboard shortcut for a new r code (Mac keyboard layout)
To see more shortcuts in the menu `Tools` → `Keyboard Shortcuts Help`.

## On the Computer

Today's lab we will use Data Carpentry tutorials for a different perspective.  Be sure to start at the section on [Starting with data](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html) then proceed to [manipulating data](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html) and a walk through of [ggplot](https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html) using Data Carpentry's tutorials. Next week we will return to working with the 23andMe and Ancestry data.

## What to upload to Canvas

Create a report using R Markdown with all the [ggplot tutorial](https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html) examples and with the challenges listed at the end.  Make sure you include code to load the data and libraries from the earlier Data Carpentry lessons.  If you are not doing this on Posit Cloud you will need to create a `data_raw` folder or modify the path when you download the `portal_data_joined.csv` file. 