---
title: "Evolutionary Genomics & Bioinformatics"
date: 'Spring 2024'
output: 
  html_document:
    theme: darkly
---

This is a rendering of hmtl files from the [course repository](https://github.com/jeffreyblanchard/EvoGeno2024R) for Evolutionary Genomics & Bioinformatics taught at the University of Massachusetts Amherst by Prof. Jeffrey Blanchard.  If you are not using RStudio (Posit) Cloud here are [Directions](EvoGeno_github.html) for creating a RStudio project space that will sync with and download files from the course repo.

* Lab 1 : [Introduction to R and Reproducible Research](EvoGeno_Lab1_intro.html)
* Lab 2 : [Rmarkdown](EvoGeno_Lab2_Rmarkdown.html)
* Lab 3 : [Data types and importing tables](EvoGeno_Lab3_data_types.html)
* Lab 4 : [Data Wrangling](EvoGeno_Lab4_datawrangle.html)
* Lab 5 : [Connecting a Github repo site with a new RStudio project](EvoGeno_Lab5_Github_posit.html)
* Lab 6 : [Data Visualization with ggplot](EvoGeno_Lab6_ggplot.html)
* Lab 7 : [Building a 5 tab web site with Quarto](EvoGeno_Lab7_quarto.html)
* Lab 8 : [Wrangling the NEON data](EvoGeno_Lab8_tables.html)
* Lab 9 : [ggplotting the NEON data](EvoGeno_Lab9_pub_graphics.html)
* Lab 10 : [National Ecological Observatory (NEON) Projects](EvoGeno_Lab10_NEON.html)
* Lab 11 : [Adding references to your report with Zotero](EvoGeno_Lab11_zotero.html)
* Lab 12 : [Table joins of NEON MAG, metagenomic and chemistry data](EvoGeno_Lab12_joins.html)

Advanced Labs

* Lab A1 : [Programming in R - Regular Expressions](EvoGeno_xtra1_stringr.html)
* Lab A3 : [Programming in R - Control Structures and Functions](EvoGeno_xtra3_loops.html)
* Lab A4 : [R Shiny](EvoGeno_xtra4_shiny.html)
* Lab A6 : [Working on the command line](EvoGeno_xtra6_cmd.html)
